import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createRun,selectStories,openTurn,submit,resolve,advance,levelFor} from '../engine.js';
const stories=JSON.parse(fs.readFileSync(new URL('../stories.json',import.meta.url)));const crew=[{id:'a',alias:'A'},{id:'b',alias:'B'},{id:'c',alias:'C'}];
test('ten unique, complete three-decision stories',()=>{assert.equal(stories.length,10);assert.equal(new Set(stories.map(s=>s.id)).size,10);for(const s of stories){assert.equal(s.scenes.length,3);for(const q of s.scenes){assert.equal(q.bad.length,3);for(const k of ['a','why','law','good','effect','plot'])assert.ok(q[k]);}}});
test('unused stories take priority and exhausted archives remain replayable',()=>{const h=stories.slice(0,7).map(s=>s.id);assert.deepEqual(selectStories(stories,[h],3,()=>.5),[7,8,9]);assert.equal(selectStories(stories,[stories.map(s=>s.id)],5).length,5);const group=selectStories(stories,[h,stories.slice(7).map(s=>s.id)],5,()=>.5);assert.equal(group.length,5);});
test('three simultaneous responses resolve immediately, once',()=>{const s=createRun(stories,[0],crew,'one');openTurn(s,1000);assert.equal(s.deadline,61000);assert.ok(submit(s,'a',0,2000));assert.equal(resolve(s,stories,2000),false);assert.equal(submit(s,'a',1,2100),false);assert.equal(submit(s,'intruder',0,2100),false);submit(s,'b',1,2200);submit(s,'c',0,2300);assert.ok(resolve(s,stories,2300));assert.equal(s.phase,'review');assert.equal(s.players[0].points,100);assert.equal(s.players[1].points,0);assert.equal(s.players[1].integrity,56);assert.equal(resolve(s,stories,99999),false);assert.equal(s.log.length,1);});
test('hard deadline rejects late answers and penalises only missing players',()=>{const s=createRun(stories,[0],crew,'two');openTurn(s,0);submit(s,'a',0,59999);assert.equal(submit(s,'b',0,60000),false);assert.ok(resolve(s,stories,60000));assert.deepEqual(s.log[0].results.map(r=>r.timeout),[false,true,true]);assert.equal(s.players[0].correct,1);assert.equal(s.players[1].streak,0);});
test('15 decision cap, solo breaks, score bounds, rank and review retention',()=>{const s=createRun(stories,[0,1,2,3,4],[crew[0]],'three');let breaks=0;for(let i=0;i<15;i++){if(s.phase==='break'){breaks++;advance(s,'a');}assert.equal(s.phase,'explore');openTurn(s,i*100000);submit(s,'a',0,i*100000+1);resolve(s,stories,i*100000+1);advance(s,'a');}assert.equal(s.phase,'end');assert.equal(breaks,4);assert.equal(s.log.length,15);assert.equal(s.players[0].points,1825);assert.equal(s.players[0].integrity,100);assert.equal(levelFor(1825),'Nightshift Legend');assert.throws(()=>createRun(stories,[0,1,2,3,4,5],crew,'bad'));assert.throws(()=>createRun(stories,[0],[...crew,{id:'d'}],'bad'));});
test('streak resets on a wrong answer and no score falls below zero',()=>{const s=createRun(stories,[0],[crew[0]],'four');for(const c of [0,1,0]){openTurn(s,0);submit(s,'a',c,1);resolve(s,stories,1);advance(s,'a');}assert.equal(s.players[0].points,160);assert.equal(s.players[0].streak,1);assert.equal(s.players[0].best,1);});
