import {riskFor,endingFor} from './consequences.js?v=alert1';
import {playCinematic} from './cinematics.js?v=ending1';
import {createWorld} from './world.js?v=motion1';
import {Sound} from './audio.js?v=alert1';
import {Room} from './online.js';
import {selectStories,createRun,sceneFor,openTurn,submit,resolve,advance,levelFor} from './engine.js?v=alert1';
const $=s=>document.querySelector(s),ui=$('#ui'),sound=new Sound();
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=crypto.randomUUID();let seen=[],records=[];try{seen=JSON.parse(localStorage.getItem('nightshift-v3-seen')||'[]');records=JSON.parse(localStorage.getItem('nightshift-v3-records')||'[]');if(!Array.isArray(seen))seen=[];if(!Array.isArray(records))records=[];}catch{}
let filmActive=false,creditsRun=null;
function film(kind){if(filmActive)return;filmActive=true;return playCinematic(kind,{muted:kind==='opening'||!sound.enabled,onStart:()=>{world?.setEnabled(false);if(sound.ambient)sound.ambient.gain.value=0;},onFinish:()=>{filmActive=false;world?.setEnabled(screen==='explore');if(sound.ambient)sound.ambient.gain.value=sound.enabled?.016:0;}});}
let stories=[],state=null,room=null,world=null,screen='home',lastRender='',savedTurns=new Set(),lastCue=-1,closeAt=0,username='',quality=false,pendingChoice=null;
const config=window.NIGHTSHIFT_SUPABASE;const client=window.supabase&&config?.url?window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}):null;
const act='https://www.meity.gov.in/static/uploads/2024/06/2bf1f0e9f04e6fb4f8fef35e82c42aa5.pdf';const rules='https://www.meity.gov.in/static/uploads/2025/11/53450e6e5dc0bfa85ebd78686cadad39.pdf';
function notify(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),4300);}
function store(){try{localStorage.setItem('nightshift-v3-seen',JSON.stringify(seen));localStorage.setItem('nightshift-v3-records',JSON.stringify(records.slice(-30)));}catch{notify('Browser storage unavailable. History lasts for this visit only.');}}
function bind(sel,fn){const el=$(sel);if(el)el.onclick=fn;}
function view(html,name='home'){screen=name;$('#exit').hidden=!state;if(name!=='explore')$('#toast').classList.remove('show');document.body.className='phase-'+name;ui.innerHTML=html;ui.scrollTop=0;world?.setEnabled(name==='explore'&&!filmActive);$('#hud').hidden=!state||['home','lobby','guide','archive','break','end'].includes(name);}
function panel(content,extra=''){return `<section class="panel ${extra}">${content}</section>`;}
function button(id,text,primary=false){return `<button id="${id}" class="${primary?'primary':'secondary'}">${text}</button>`;}
function legalNote(){return `<p class="fine">FUTURE COMPLIANCE SIMULATION · The Act and 2025 Rules commence in phases. As at 7 October 2026, many operational duties tested here are not yet in force. Scenarios assume the relevant provisions apply; exemptions and other laws may change the result. <a href="${act}" target="_blank" rel="noopener">Act</a> / <a href="${rules}" target="_blank" rel="noopener">Rules</a> / <a href="https://www.meity.gov.in/static/uploads/2025/11/c56ceae6c383460ca69577428d36828b.pdf" target="_blank" rel="noopener">Act commencement</a>. Educational, not legal advice.</p>`;}
function home(){state=null;lastRender='';world?.setMode('home');view(`<section class="home"><div class="eyebrow">INDIA / 01:17 AM / YOUR SHIFT STARTS NOW</div><h1>The city is still<em>collecting.</em></h1><p class="lede">Ten incidents. One very long night.<br>Follow the data. Challenge the shortcuts.<br>Try to leave people better than you found them.</p><div class="row">${button('solo','CLOCK IN SOLO ↗',true)}${button('online','ASSEMBLE A CREW')}</div><div class="facts"><div><b>10</b><span>LINKED CASE FILES</span></div><div><b>1—3</b><span>PLAYERS PER SHIFT</span></div><div><b>60s</b><span>ONLINE DECISION CLOCK</span></div></div><div class="row"><button id="archive" class="small">CASE ARCHIVE · ${seen.length}/10 EXPLORED</button><button id="history" class="small">MY SHIFT RECORD</button><button id="watch-intro" class="small">WATCH OPENING</button><button id="watch-team" class="small">TEAM CREDITS</button></div><p class="caption">A 3D privacy noir, grounded in India’s DPDP Act & Rules.<br>No capes. No magic consent checkbox. Just your judgement.</p><p class="fine">Keyboard + mouse or touch · headphones recommended<br>Fictional future setting after applicable provisions commence.</p></section><aside class="world-note"><span class="eyebrow">LIVE FROM THE OPERATIONS FLOOR</span><strong>Somebody clicked “export all”.</strong><p>The rain hasn’t stopped.<br>Neither has the incident queue.</p></aside>`);bind('#solo',soloSetup);bind('#online',onlineSetup);bind('#archive',archive);bind('#history',history);bind('#watch-intro',()=>film('opening'));bind('#watch-team',()=>film('credits'));}
function soloSetup(){view(panel(`<span class="eyebrow">SOLO / CHOOSE YOUR SHIFT</span><h2>How much night have you got?</h2><p>Walk the operations floor and work a chain of incidents. Read each outcome at your pace. Between cases, take a coffee break or return to the floor.</p><div class="fields"><label>SHIFT LENGTH<select id="length"><option value="2">Quick patrol — 2 stories / 6 decisions</option><option value="3" selected>Nightshift — 3 stories / 9 decisions</option><option value="5">Double shift — 5 stories / 15 decisions</option></select></label></div><p class="fine">Fresh stories are prioritised using this browser’s completed-case history. After the archive is exhausted, familiar stories become replayable.</p><div class="row">${button('begin','ENTER OPERATIONS ↗',true)}${button('back','BACK')}</div>${legalNote()}`));bind('#back',home);bind('#begin',()=>{sound.start();const route=selectStories(stories,[seen],Number($('#length').value));start(createRun(stories,route,[{id,alias:'You'}],crypto.randomUUID()));});}
function onlineSetup(){view(panel(`<span class="eyebrow">SUPABASE / ONLINE CASE ROOM</span><h2>Good judgement. Better company.</h2><p>Up to three players answer the same incident. Lock your own response. Everyone locked? Results appear immediately. Otherwise the 60-second deadline decides. No mission breaks in multiplayer.</p><div class="fields"><label>YOUR SESSION USERNAME<input id="username" maxlength="18" placeholder="e.g. NightOwl" autocomplete="off" spellcheck="false"></label></div><p class="fine">Your username is not stored in a database or browser storage. It is shared with your room and held in session memory for the leaderboard, then cleared when the leaderboard closes (automatically after 5 minutes). Use a nickname; other players can see it.</p><div class="row">${button('create','CREATE ROOM',true)}<input id="room-code" maxlength="6" placeholder="6-LETTER CODE" aria-label="Room code" style="width:175px;margin:0">${button('join','JOIN')}</div><p id="room-status" role="status"></p><div class="row">${button('back','BACK')}</div>${legalNote()}`));bind('#back',home);bind('#create',()=>connect(true));bind('#join',()=>connect(false));}
async function connect(host){username=$('#username').value.trim();if(!username){$('#room-status').textContent='Choose a session username first.';$('#username').focus();return;}const code=host?Array.from(crypto.getRandomValues(new Uint8Array(6)),b=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[b%31]).join(''):$('#room-code').value.trim().toUpperCase();if(!/^[A-Z2-9]{6}$/.test(code)){$('#room-status').textContent='Use the six-character room code from your host.';return;}if(!client){$('#room-status').textContent='Online service unavailable. Solo play is ready.';return;}$('#room-status').textContent='Connecting to the operations network…';$('#create').disabled=$('#join').disabled=true;
 room=new Room(client,id,receive,(m)=>{const el=$('#room-status');if(el)el.textContent=m;else notify(m);},m=>exitRoom(m));room.onAction=hostAction;
 try{await room.connect(code,host,username,seen);sound.start();lobby();if(host)room.snapshot();}catch(e){await room?.close();room=null;onlineSetup();$('#room-status').textContent=e.message;}}
function lobby(){if(!room)return;const old=$('#length')?.value||'3';view(panel(`<span class="eyebrow">ONLINE / ${room.host?'HOST':'CREW MEMBER'}</span><h2>The room is open.</h2><p>Send this code to your crew. Everyone joins before the shift starts.</p><div class="code">${esc(room.code)}</div><div id="crew" class="crew"></div><p id="room-status" role="status">${room.host?'You control when the shift starts.':'Waiting for host admission…'}</p>${room.host?`<div class="row"><label for="length">Shift length</label><select id="length"><option value="2">6 decisions</option><option value="3" selected>9 decisions</option><option value="5">15 decisions</option></select></div>`:''}<div class="row">${room.host?button('launch','START SHARED SHIFT ↗',true):''}${button('leave','LEAVE ROOM')}</div><p class="fine">Usernames are session-only. Leaderboard closes and clears them after five minutes. No persistent online score or username is written. Keep the host’s tab open.</p>`),'lobby');if($('#length'))$('#length').value=old;renderCrew();bind('#leave',()=>exitRoom());bind('#launch',()=>{const route=selectStories(stories,room.crew.map(p=>p.seen),Number($('#length').value));const s=createRun(stories,route,room.crew.map(p=>({id:p.id,alias:p.alias})),crypto.randomUUID());openTurn(s,Date.now());room.state=s;room.snapshot();});}
function renderCrew(){if(!room)return;const el=$('#crew');if(el)el.innerHTML=room.crew.map(p=>`<span>● ${esc(p.alias)}${p.id===id?' / YOU':''}</span>`).join('');const status=$('#room-status');if(status&&room.crew.some(p=>p.id===id))status.textContent=`${room.crew.length}/3 CONNECTED · ${room.host?'Ready when you are.':'Waiting for the host to start.'}`;}
function start(s){state=s;savedTurns=new Set();lastCue=-1;pendingChoice=null;lastRender='';world?.setMode('play');world?.setTarget(s.route[0],true);render();}
function receive(s){if(!room)return;if(!s){renderCrew();return;}if(!state||state.id!==s.id){start(s);return;}if(s.rev<state.rev)return;state=s;render();}
function publish(){if(room){room.state=state;room.snapshot();}else render();}
function hostAction(m){if(!room?.host||!state||m.run!==state.id)return;if(m.action==='answer'&&m.turn===state.turn){if(submit(state,m.from,m.choice,Date.now())){if(resolve(state,stories,Date.now()))state.nextAt=Date.now()+8000;publish();}}if(m.action==='ready'&&m.turn===state.turn&&state.phase==='review'){if(!state.ready.includes(m.from))state.ready.push(m.from);if(state.ready.length===state.players.length)nextOnline();else{state.rev++;publish();}}}
function nextOnline(){if(!state||state.phase!=='review')return;state.turn++;state.locks={};state.ready=[];state.rev++;if(state.turn>=state.route.length*3){state.phase='end';state.endsAt=Date.now()+300000;}else{state.phase='explore';openTurn(state,Date.now());}publish();}
function currentStory(){return stories[state.route[Math.min(Math.floor(state.turn/3),state.route.length-1)]];}
function mine(){return state.players.find(p=>p.id===id)||state.players[0];}
function remember(){for(const entry of state.log){if(entry.scene!==2)continue;const key=state.id+':'+entry.story;if(savedTurns.has(key))continue;savedTurns.add(key);const sid=stories[entry.story].id;if(!seen.includes(sid))seen.push(sid);store();}if(state.phase==='end'&&!savedTurns.has('end')){savedTurns.add('end');if(!room){records.push({at:new Date().toISOString(),points:mine().points,correct:mine().correct,total:state.log.length,best:mine().best,integrity:mine().integrity});store();}}}
function hud(){const p=mine();$('#points').textContent=p.points;$('#integrity').textContent=p.integrity+'/100';$('#streak').textContent=p.streak;$('#level').textContent=levelFor(p.points);$('#sector').textContent=currentStory().sector+' / CASE '+Math.min(state.route.length,Math.floor(state.turn/3)+1)+' OF '+state.route.length;$('#objective').textContent=currentStory().title;}
function render(){if(!state)return;remember();hud();const key=state.id+':'+state.phase+':'+state.turn;if(key===lastRender){updateLocks();return;}lastRender=key;pendingChoice=null;world?.setMode('play');world?.setTarget(state.route[Math.min(Math.floor(state.turn/3),state.route.length-1)],!!room||state.turn%3===0);if(state.phase==='explore'){view('','explore');notify(state.turn%3===0?currentStory().brief:'Follow the next lead at the active terminal.');}if(state.phase==='decision')decision();if(state.phase==='review')review();if(state.phase==='break')missionBreak();if(state.phase==='end')ending();}
function interact(what){if(!state||state.phase!=='explore')return;if(what==='coffee'){sound.cue(true);notify('Coffee acquired. It cannot fix consent, but it can keep you awake.');return;}if(['map','drone','inactive'].includes(what)){sound.cue(true);notify(what==='map'?'Room scan complete. Live data routes highlighted; your assignment is the glowing terminal.':what==='drone'?'Patrol drone acknowledged. Route reversed. It has better boundaries than the marketing team.':'This terminal belongs to another case. Follow the glowing marker for your active assignment.');return;}if(what==='far'){notify('Walk to the glowing terminal, or use Navigate to case.');return;}openTurn(state,Date.now());publish();}
function previous(){const prev=state.log.at(-1);if(!prev)return '';const result=prev.results.find(p=>p.id===id);const sc=stories[prev.story].scenes[prev.scene];return `<p class="bridge">YOUR LAST CALL → ${esc(result.good?sc.good:sc.effect)}</p>`;}
function decision(){const story=currentStory(),sc=sceneFor(state,stories);let options=[sc.a,...sc.bad].map((text,i)=>({text,i}));const offset=(state.turn+state.id.charCodeAt(0))%4;options=options.slice(offset).concat(options.slice(0,offset));
 view(panel(`<div class="case-top"><span class="eyebrow">${room?'CREW':'SOLO'} / DECISION ${state.turn+1} OF ${state.route.length*3}</span>${room?'<span class="timer" id="clock">60s</span>':'<span class="eyebrow">NO RUSH</span>'}</div><div class="progress"><i style="width:${state.turn/(state.route.length*3)*100}%"></i></div><span class="eyebrow">${esc(story.sector)} / ${esc(sc.evidence)}</span>${riskReminder()}<h2>${esc(story.title)}</h2><div class="transmission"><div class="portrait">${esc(story.speaker[0])}</div><div><small>${esc(story.speaker)} · SECURE LINE</small><p>${esc(state.turn%3===0?story.joke:sc.plot)}</p></div></div>${state.turn%3===0?`<p>${esc(sc.plot)}</p>`:previous()}<p class="question">${esc(sc.q)}</p><div class="choices">${options.map((o,n)=>`<button class="choice" data-choice="${o.i}"><kbd>${n+1}</kbd><span>${esc(o.text)}</span></button>`).join('')}</div><p class="fine" id="lock-status">${room?'60 seconds. One response each. Your answer is final once locked.':'Choose the response you can defend at the morning review.'}</p>${room?'<div id="live-board" class="room-strip"></div>':''}`,'case-panel'),'decision');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(Number(b.dataset.choice)));updateLocks();}
function answer(choice){if(!state||state.phase!=='decision'||pendingChoice!==null)return;sound.start();if(room){pendingChoice=choice;updateLocks();room.action('answer',{run:state.id,turn:state.turn,choice});}else{submit(state,id,choice,Math.min(Date.now(),state.deadline-1));resolve(state,stories,state.deadline);publish();}}
function updateLocks(){if(!state)return;if(state.phase==='decision'){const locked=Object.hasOwn(state.locks,id);if(locked)pendingChoice=state.locks[id];if(pendingChoice!==null){document.querySelectorAll('.choice').forEach(b=>{b.disabled=true;b.classList.toggle('chosen',Number(b.dataset.choice)===pendingChoice);});}const el=$('#lock-status');if(el&&room)el.textContent=`${Object.keys(state.locks).length}/${state.players.length} RESPONSES LOCKED · ${locked?'Your response is locked.':pendingChoice!==null?'Sending…':'Choose before the deadline.'}`;const board=$('#live-board');if(board)board.textContent=state.players.map(p=>`${p.alias}: ${p.points} pts${Object.hasOwn(state.locks,p.id)?' ✓':''}`).join(' / ');}if(state.phase==='review'){const b=$('#continue');if(b&&state.ready.includes(id)){b.disabled=true;b.textContent='READY · WAITING FOR CREW';}}}
function consequenceWarning(r,sc){
 const risk=riskFor(state.log,id,mine().integrity),before=r.before,after=r.after||mine();
 return `<section class="consequence-alert ${risk.severity}" role="alert" aria-label="Decision consequence"><span class="eyebrow">⚠ ${r.timeout?'DEADLINE MISSED · ':''}${risk.title}</span><h3>${r.timeout?'No response. The risk went unchallenged.':'Your decision put people at risk.'}</h3><p class="harm"><strong>CONSEQUENCE</strong><br>${esc(sc.effect)}</p><div class="penalty-grid"><div><small>POINTS · −40 PENALTY</small><b>${before?before.points+' → ':''}${after.points}</b>${after.points===0?'<small>Score cannot fall below zero.</small>':''}</div><div><small>INTEGRITY · −14</small><b>${before?before.integrity+' → ':''}${after.integrity}/100</b></div><div><small>STREAK RESET</small><b>${before?before.streak+' → ':''}0</b></div></div><p class="safer"><strong>SAFER RESPONSE</strong><br>${esc(sc.a)}</p><p class="fine">${esc(risk.guidance)}${risk.consecutive>1?' '+risk.consecutive+' consecutive unsafe calls.':''}</p></section>`;
}
function review(){const entry=state.log.at(-1),sc=stories[entry.story].scenes[entry.scene],r=entry.results.find(p=>p.id===id);
 if(lastCue!==state.turn){r.good?sound.cue(true):sound.warning();world?.respond(r.good);lastCue=state.turn;}
 view(panel(`${!r.good?consequenceWarning(r,sc):'<span class="eyebrow">DECISION DEFENSIBLE</span><h2>One less problem at sunrise.</h2>'}<div class="feedback ${r.good?'good':''}"><span class="eyebrow">${r.good?'WHY IT WORKS':'WHY THIS WAS UNSAFE'}</span><p><strong>Your call:</strong> ${esc(r.timeout?'No answer within 60 seconds.':[sc.a,...sc.bad][r.choice])}</p><p>${esc(sc.why)}</p>${r.good?'<p><strong>Effect:</strong> '+esc(sc.good)+'</p>':''}<p class="legal">${esc(sc.law)}</p></div>${r.good?'<p class="fine">+'+r.delta+' POINTS · +8 INTEGRITY (up to 100) · STREAK '+mine().streak+'</p>':''}${room?leaderboard(false):''}${!r.good&&!room?'<button id="acknowledge" class="warning-ack">I UNDERSTAND THE CONSEQUENCE</button><p class="fine">Acknowledge the warning to continue. Your penalty remains.</p>':''}<div class="row">${button('continue',room?'READY FOR NEXT QUESTION →':state.turn===state.route.length*3-1?'FINISH SHIFT →':'FOLLOW THE LEAD →',true)}${!room?button('explore','RETURN TO FLOOR'):''}</div>${room?'<p class="fine" id="review-clock">Next question in 8s. All ready moves on immediately.</p>':''}`,'case-panel'),'review');
 if(!r.good){document.body.classList.add('unsafe-review');if(!room){$('#continue').disabled=$('#explore').disabled=true;bind('#acknowledge',()=>{$('#continue').disabled=$('#explore').disabled=false;$('#acknowledge').disabled=true;$('#acknowledge').textContent='WARNING ACKNOWLEDGED';$('#continue').focus();});}}
 bind('#continue',()=>{if(room)room.action('ready',{run:state.id,turn:state.turn});else{advance(state,id);publish();if(state.phase==='explore')interact('case');}});bind('#explore',()=>{advance(state,id);publish();});
}
function riskReminder(){const risk=riskFor(state.log,id,mine().integrity);return risk.consecutive||mine().integrity<=30?`<div class="risk-reminder" role="status">⚠ ${mine().integrity<=30?'CRITICAL INTEGRITY':risk.consecutive+' UNSAFE CALL'+(risk.consecutive===1?'':'S')+' IN A ROW'} · ${mine().integrity}/100 integrity. A wrong answer costs 40 points, 14 integrity and your streak. Check the evidence before you lock in.</div>`:'';}
function missionBreak(){view(panel(`<span class="eyebrow">SOLO INTERMISSION / CASE FILE SEALED</span><h2>The coffee has filed a grievance.</h2><p>One story closed. ${mine().integrity>=70?'You’ve kept the incident under control.':'The city is feeling the effects of those shortcuts.'} Take a breath before the next call.</p><div class="feedback good"><span class="eyebrow">NEXT LEAD / ${esc(currentStory().sector)}</span><h3>${esc(currentStory().title)}</h3><p>${esc(currentStory().brief)}</p></div><p class="fine">No timer during solo mission breaks. Stretch, get water, or explore the floor.</p><div class="row">${button('resume','TAKE THE NEXT CASE →',true)}${button('walk','COFFEE & FLOOR WALK')}</div>`),'break');bind('#resume',()=>{advance(state,id);publish();interact('case');});bind('#walk',()=>{advance(state,id);publish();});}
function leaderboard(final){const players=[...state.players].sort((a,b)=>b.points-a.points||b.integrity-a.integrity||b.correct-a.correct);return `<h3>${final?'Shift leaderboard':'Live standings'}</h3><table><thead><tr><th>RANK</th><th>ANALYST</th><th>POINTS</th><th>INTEGRITY</th><th>STREAK</th></tr></thead><tbody>${players.map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.alias)}${p.id===id?' · YOU':''}</td><td>${p.points}</td><td>${p.integrity}/100</td><td>${final?p.best:p.streak}${final?' best':''}</td></tr>`).join('')}</tbody></table>`;}
function debrief(){return state.log.map(e=>{const sc=stories[e.story].scenes[e.scene],r=e.results.find(x=>x.id===id);return `<details><summary>${r.good?'✓':'✕'} ${e.turn+1}. ${esc(stories[e.story].title)} · ${esc(sc.tag)} ${r.timeout?' / TIMEOUT':''}</summary><p><strong>Your call:</strong> ${esc(r.timeout?'No response before the deadline.':[sc.a,...sc.bad][r.choice])}</p><p><strong>Best response:</strong> ${esc(sc.a)}</p><p><strong>${r.good?'Why it worked':'What went wrong'}:</strong> ${esc(sc.why)}</p><p><strong>Effect:</strong> ${esc(r.good?sc.good:sc.effect)}</p><p class="legal">${esc(sc.law)}</p></details>`;}).join('');}
async function endingSequence(runId,kind){await film(kind);if(state?.id===runId&&state.phase==='end')await film('credits');}
function ending(){const p=mine(),outcome=endingFor(p.correct,state.log.length),accuracy=Math.floor(p.correct/state.log.length*100);closeAt=room?(state.endsAt||Date.now()+300000):0;view(panel(`<span class="eyebrow">06:00 AM / SHIFT COMPLETE</span><h2>${outcome==='good-ending'?'You held the line. The city wakes safer.':'Trust went dark. The night is not over.'}</h2><p class="ending-verdict ${outcome}">${accuracy}% CORRECT · ${outcome==='good-ending'?'HEROIC ENDING — 80% TARGET MET':'DARK ENDING — BELOW 80%'}</p><p>${p.correct===state.log.length?'Every decision held up. The shortcuts didn’t get a vote.':`${state.log.length-p.correct} decision${state.log.length-p.correct===1?' needs':'s need'} a closer look. Open the incident reviews below to see the choice, the legal reason and the effect.`}</p><div class="scorehero"><div><b>${p.points}</b><span>POINTS</span></div><div><b>${p.correct}/${state.log.length}</b><span>DEFENSIBLE CALLS</span></div><div><b>${p.integrity}</b><span>INTEGRITY</span></div></div><span class="eyebrow">LEVEL / ${esc(levelFor(p.points))}</span>${room?leaderboard(true):''}<h3>Your incident review</h3>${debrief()}${room?'<p class="fine" id="erase-clock">Usernames are held only in this session. Closing the leaderboard clears this session. It closes automatically after five minutes.</p>':'<p class="fine">Your completed cases and solo score are saved in this browser. No username is stored.</p>'}<div class="row">${button('finish',room?'CLOSE LEADERBOARD & CLEAR USERNAME':'CLOCK OUT →',true)}${button('replay-ending','REPLAY YOUR ENDING')}${button('replay-credits','REPLAY CREDITS')}</div>${legalNote()}`,'wide'),'end');bind('#finish',()=>room?exitRoom():home());bind('#replay-credits',()=>film('credits'));bind('#replay-ending',()=>endingSequence(state.id,outcome));if(creditsRun!==state.id){creditsRun=state.id;endingSequence(state.id,outcome);}}
async function exitRoom(message){const r=room;room=null;state=null;username='';pendingChoice=null;closeAt=0;ui.innerHTML='';await r?.close();home();if(message)notify(message);}
function archive(){view(panel(`<span class="eyebrow">CASE ARCHIVE / TEN CONNECTED NIGHTS</span><h2>Every shortcut leaves a trail.</h2><div class="archive">${stories.map((s,i)=>`<article><small>${String(i+1).padStart(2,'0')} / ${esc(s.sector)} · ${seen.includes(s.id)?'COMPLETED':'UNEXPLORED'}</small><h3>${esc(s.title)}</h3><p>${esc(s.brief)}</p></article>`).join('')}</div><div class="row">${button('back','BACK TO OPERATIONS',true)}</div>`,'wide'),'archive');bind('#back',home);}
function history(){view(panel(`<span class="eyebrow">THIS BROWSER ONLY / SOLO HISTORY</span><h2>Your morning handovers.</h2>${records.length?`<table><thead><tr><th>DATE</th><th>POINTS</th><th>CORRECT</th><th>INTEGRITY</th></tr></thead><tbody>${records.slice(-10).reverse().map(r=>`<tr><td>${esc(new Date(r.at).toLocaleDateString())}</td><td>${r.points}</td><td>${r.correct}/${r.total}</td><td>${r.integrity}</td></tr>`).join('')}</tbody></table>`:'<p>No completed solo shifts yet. The city is waiting.</p>'}<p class="fine">${seen.length}/10 completed cases remembered. Online usernames and leaderboards are never saved here.</p><div class="row">${button('back','BACK',true)}${button('clear','RESET COMPLETED-CASE HISTORY')}</div>`));bind('#back',home);bind('#clear',()=>{seen=[];store();history();notify('Completed-case history reset. Solo scores retained.');});}
function guide(){if(state&&room){notify('Online clock keeps running. Drag to look, WASD to move; choose a response to lock it.');return;}const old=screen;view(panel(`<span class="eyebrow">FIELD GUIDE / READ THE FINE PRINT</span><h2>Make the call. Own the effect.</h2><p><strong>Move:</strong> WASD or arrow keys. Drag the 3D scene to look in any direction; Q / R turn by keyboard. E inspects a nearby active terminal. Navigate to case offers an accessible shortcut. Touch controls work on phones. Click or tap a nearby terminal, patrol drone, holographic city map or coffee machine. E also interacts with the object at the centre of your view. Scan room sends a visible pulse through the data conduits. Drones acknowledge a tap by hovering and reversing their route.</p><p><strong>Points:</strong> +100 per correct call; +25 bonus from your third consecutive correct call. Wrong answers and online timeouts cost 40, with a zero floor. Integrity starts at 70, changes by +8 or −14 and stays between 0 and 100. Streak resets on a miss.</p><p><strong>Levels:</strong> Desk Rookie → Consent Detective (350) → Incident Commander (700) → Privacy Sentinel (1050) → Nightshift Legend (1400).</p><p><strong>Online:</strong> everyone answers simultaneously. All submitted resolves immediately, otherwise 60 seconds is final. Results stay for up to 8 seconds; all ready advances sooner. No mission intermissions. The host must remain connected. Session leaderboard ranks points, then integrity, then correct calls.</p><p><strong>History:</strong> only completed stories are remembered locally, per browser. Group selection prioritises stories unfamiliar to the most players. Clearing browser data clears that history. Usernames remain in memory and are not persisted.</p>${legalNote()}<p class="fine">Rule 1 brings Rules 1, 2 and 17–21 into force on publication, Rule 4 after one year, and Rules 3, 5–16, 22 and 23 after eighteen months. Act provisions have their own commencement notification. This game does not imply that every provision is currently enforceable.</p><div class="row">${button('back','RETURN',true)}</div>`),'guide');bind('#back',()=>{if(state){lastRender='';render();}else home();});}
bind('#exit',()=>{if(room)exitRoom();else home();});bind('#audio',()=>{$('#audio').textContent=sound.toggle()?'SOUND ON':'SOUND OFF';});bind('#quality',()=>{quality=!quality;world?.setQuality(quality);$('#quality').textContent=quality?'HIGH FX':'LOW FX';});bind('#help',guide);bind('#inspect',()=>world?world.interact():interact('case'));bind('#scan',()=>world?.scan());bind('#guide',()=>{world?.guide();notify('At the active terminal. Inspect to open the case.');});bind('#quit',()=>{if(room)exitRoom();else home();});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);world?.move(b.dataset.key,true);};b.onpointerup=b.onpointercancel=()=>world?.move(b.dataset.key,false);});
addEventListener('keydown',e=>{if(filmActive||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(screen==='decision'&&/^[1-4]$/.test(e.key))document.querySelectorAll('.choice')[Number(e.key)-1]?.click();});
setInterval(()=>{if(!state)return;const now=Date.now();if(room&&state.phase==='decision'){const clock=$('#clock');if(clock){const left=Math.max(0,Math.ceil((state.deadline-now)/1000));clock.textContent=left+'s';clock.classList.toggle('urgent',left<=10);}if(room.host&&resolve(state,stories,now)){state.nextAt=now+8000;publish();}if(pendingChoice!==null&&!Object.hasOwn(state.locks,id)&&now<state.deadline)room.action('answer',{run:state.id,turn:state.turn,choice:pendingChoice});}if(room&&state.phase==='review'){const el=$('#review-clock');if(el)el.textContent=`Next question in ${Math.max(0,Math.ceil((state.nextAt-now)/1000))}s · all ready advances immediately.`;if(room.host&&now>=state.nextAt)nextOnline();}if(room&&state.phase==='end'&&now>=closeAt)exitRoom('Leaderboard closed. Session usernames cleared.');},250);
try{stories=await fetch('./stories.json').then(r=>{if(!r.ok)throw Error('Case archive unavailable');return r.json();});try{world=createWorld($('#world'),interact);}catch(e){notify('3D unavailable on this device. Accessible terminal play is still available.');}home();film('opening');}catch(e){view(panel(`<h2>The archive did not load.</h2><p>${esc(e.message)}</p><button onclick="location.reload()" class="primary">RETRY</button>`));}
