import fs from 'node:fs';
const original=fs.readFileSync('../app/src/stories.ts','utf8');
const stories=Function('return '+original.match(/const STORIES: StoryScript\[\] = (\[[\s\S]*?\n\]);/)[1])();
const bank=JSON.parse(fs.readFileSync('scenarios.json','utf8'));
const extras=[
['SIGNAL LAB','MIRA / QA','A fitness launch is harvesting more than steps. Follow the permissions to the advertising exchange.','The button says Allow. The roadmap says allow everything.',['The location stream waits for a meaningful choice. Mira keeps the release in staging.','The delivery list stays out of the promotion queue. Marketing discovers the existence of purposes.','Separate controls survive launch. Users can receive safety alerts without sponsoring an ad exchange.'],['Location flows before users understand it. Mira finds coordinates in the release logs.','Delivery numbers enter a promotional campaign. Customers learn their courier has become a salesperson.','One checkbox forces unrelated uses together. The consent trail cannot show a specific choice for advertising.']],
['SWITCHBOARD','MIRA / CUSTOMER','An opt-out exposes a retention machine. Help one person reclaim control without losing the service.','Our unsubscribe journey has nine screens. The hero’s journey only had twelve.',['Personalised offers stop; separately justified account functions keep working.','Withdrawal becomes as easy as consent. Support closes the maze-related tickets.','Mira gets a route through a registered Consent Manager, accountable to her.'],['Mira’s choice is ignored or her whole account is unnecessarily destroyed. Neither respects her specific request.','The withdrawal obstacle course keeps processing alive after the user tries to stop it.','An unregistered intermediary acquires permissions it cannot manage as a statutory Consent Manager.']],
['CIVIC NODE','DEV / CITY OPS','A grant application grows tentacles. Trace its data appetite from one form to a government request.','Fraud prevention needs your aunt’s contacts. Apparently fraud has an aunt.',['The form asks only for relevant eligibility information. Applicants keep unrelated data to themselves.','Speculative collection stops until a lawful, specific purpose and basis exist.','The office identifies the statutory function and conditions before processing.'],['Applicants surrender unrelated data for a grant. The portal creates exposure without a justified purpose.','The city accumulates data for an imaginary future use. Maybe later is not a lawful ground.','An official letter becomes an unlimited request. Government status cannot justify every use.']],
['JUNIOR NETWORK','NILA / SAFETY','A learning game turns children into ad segments. Find the tracker, check the parent, fix the rights desk.','Children learn maths. The ad network learns the children.',['Behavioural advertising stops. Applicable child protections and verifiable parental consent are checked.','The adult’s identity and age are checked appropriately before parental consent is relied on.','The guardian can use an accessible rights channel without broadcasting the child’s details.'],['Children become behavioural advertising targets. A free game does not remove protection.','A sixteen-year-old’s click stands in for adult consent. A checkbox has not become a parent.','A guardian cannot exercise rights. An inaccessible form is a locked door with a help icon.']],
['VENDOR DOCK','RAFI / ENGINEERING','An appointment vendor brings a subcontractor and a convenient theory of responsibility.','The vendor says they own the problem. Their contract says they own a beanbag.',['A valid contract limits reminder processing and protects customer details.','Subcontractor access waits until purpose, contract and safeguards are checked.','The fiduciary owns its duties while coordinating the vendor response.'],['Customer numbers are shared on a handshake. The vendor can drift beyond the appointment purpose.','Identifiable events reach an unchecked subcontractor. An NDA cannot legitimise unrestricted reuse.','Response stalls while everyone blames the processor. The fiduciary’s statutory duties remain.']],
['INCIDENT VAULT','RAFI / RESPONSE','A personal drive becomes a breach. Contain it and get the truth to affected people.','Someone named the folder FINAL_secure_v7. The folder took that personally.',['The sync is contained; evidence is preserved and breach duties are assessed.','The fiduciary owns notification compliance instead of assuming the cloud vendor will.','Initial notices start without delay; detailed Board information follows within 72 hours unless extended on written request.'],['Exposure continues or evidence disappears. The team loses the means to understand and contain the breach.','People wait while vendor and company point at each other. Outsourcing storage did not outsource accountability.','People lose time to protect themselves. The 72-hour detail window is not permission to delay initial notices.']],
['RIGHTS DESK','ASHA / SUPPORT','A missing data summary leads to a wrong name and an unanswered complaint. Make the desk work for people.','The bot apologised 46 times. This is apology-as-a-service.',['The verified requester gets the summary they are entitled to, without another person’s records.','The inaccurate name can be corrected through the rights process.','An accessible grievance mechanism gets an owner; the person can approach the Board after exhausting it.'],['A policy link replaces the summary. The user still cannot understand their actual processing.','A known error follows the person. Annual release cycles do not justify refusing a valid request.','The complaint has no useful path. Support keeps generating apologies while the problem escalates.']],
['ARCHIVE','DEV / RECORDS','Old profiles, lingering copies and a contradictory loan record. Decide what to keep, erase and correct.','We retain everything forever. It’s cheaper than deciding what anything is for.',['Unneeded extras and processor copies are erased after applicable retention requirements are checked.','Purpose-ended data is erased when no law requires retention; legally required records are separated.','Conflicting records are reconciled before a decision affecting the person.'],['Unused profiles enlarge the breach surface, or mandatory records are deleted without checking retention duties.','An archive excuses indefinite reuse, or legally required records are erased too soon.','Contradictory data drives a consequential decision. The fastest record is not necessarily accurate.']],
['BORDER RELAY','NILA / INFRA','A cloud migration meets a public-data shortcut. Follow the source, destination and responsible contact.','The cloud is someone else’s computer. The spreadsheet calls it a jurisdiction.',['The team checks notified transfer restrictions, Rule 15 requirements and stricter sector laws.','The source is checked: the public-data exclusion depends on who made it public and why.','A responsible business contact can answer processing and rights questions.'],['The team invents a universal ban or ignores actual restrictions. Either derails a lawful transfer assessment.','Public visibility is mistaken for permission. A leaked list was not made public by its Data Principals.','Users reach a cloud vendor instead of a responsible contact. Accountability becomes a forwarding loop.']],
['AUDIT CORE','BOSS / STRATEGY','A missing consent receipt, a suspicious request and an overpowered intern. Evidence beats theatre.','The audit is tomorrow. Can we backdate a culture of compliance?',['Notice and affirmative consent evidence support the permission being relied upon.','The request is verified proportionately, requiring authentic information without public shaming.','Role-appropriate access replaces broad downloads, with safeguards and logs.'],['The team cannot demonstrate agreement. Reconstructed confidence is not a consent record.','Impersonation succeeds or documents are exposed in retaliation. Neither is appropriate verification.','The intern can still export the customer base. Convenience has become a breach multiplier.']]
];
stories.forEach((s,i)=>{const [sector,speaker,brief,joke,good,bad]=extras[i];Object.assign(s,{sector,speaker,brief,joke});s.scenes=s.scenes.map((sc,j)=>({...bank.find(b=>b.id===sc.sourceId),...sc,good:good[j],effect:bad[j],evidence:['INTAKE / '+s.id.toUpperCase(),'FOLLOW THE TRAIL','CLOSE THE LOOP'][j]}));});
stories[9].scenes[1].law='DPDP Act 2023, s. 15(b), (e); secure verification supports rights handling';
stories[8].scenes[0].law+='; DPDP Rules 2025, r. 15';
stories[8].scenes[0].a='Check notified country restrictions, applicable Rule 15 requirements and stricter sector laws; the DPDP Act does not impose a universal overseas-transfer ban.';
stories[5].scenes[2].why='Rule 7 requires initial notice to the Board and each affected person without delay. Updated details go to the Board within 72 hours of awareness, or a longer period it allows on written request. Reputational discomfort is not an exception.';
fs.writeFileSync('stories.json',JSON.stringify(stories,null,2)+'\n');
